name: lichang666

on:
  push:
    branches:
      - docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Clear pnpm store
        run: pnpm store prune

      - name: Install dependencies and Build
        run: pnpm docs:build

      - name: Inter Dist Folder
        run: cd ./docs/.vitepress && mv ./dist ../../

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.lichang666 }} # 此处修改为你的Secret名称
          publish_dir: ./dist
